apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: iperf3-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: iperf3-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
